qltv/Models/Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.RentalItems = new HashSet<RentalItem>();
        }
    
        public int Bookcode { get; set; }
        public string Title { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<bool> BookStatus { get; set; }
        public Nullable<System.DateTime> Publish { get; set; }
        public byte[] IMG { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalItem> RentalItems { get; set; }
    }
}

qltv/ViewModels/BookView.cs
using qltv.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace qltv.ViewModels
{
    public class BookView
    {
        public IEnumerable<Book> Books { get; set; }
        public IEnumerable<Book> BorrowBook { get; set; }
        public IEnumerable<Book> AvailableBook { get; set; }

        public string Title { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<bool> BookStatus { get; set; }
        public Nullable<System.DateTime> Publish { get; set; }
        public byte[] IMG { get; set; }
        public virtual Author Author1 { get; set; }
        public virtual Genre Genre { get; set; }
    }
}

qltv/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using qltv.Models;
using qltv.ViewModels;

namespace qltv.Controllers
{
    public class BooksController : Controller
    {
        private qltvEntities db = new qltvEntities();

        // GET: Books
        public ActionResult Index(string SearchString, double min = double.MinValue, double max = double.MaxValue)
        {
            var books = db.Books.Include(b => b.Genre);
            var borrowBooks = db.Books.Include(b => b.Genre).Where(b => b.BookStatus == true);
            var availableBooks = db.Books.Include(b => b.Genre).Where(b => b.BookStatus == false);

            if (!String.IsNullOrEmpty(SearchString))
            {
                books = books.Where(s => s.Title.Contains(SearchString));
            }
            if (min >= 0 && max > 0)
            {
                books = db.Books.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }

            var viewModel = new BookView
            {
                Books = books.ToList(),
                BorrowBook = borrowBooks.ToList(),
                AvailableBook = availableBooks.ToList()

            };
            return View(viewModel);

        }


        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.Author = new SelectList(db.Authors, "AuthorID", "AuthorName");
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Bookcode,Title,Author,GenreID,Price,Available,BookStatus,Publish")] Book book, HttpPostedFileBase IMG)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (IMG != null && IMG.ContentLength > 0)
                    {
                        using (var binaryReader = new BinaryReader(IMG.InputStream))
                        {
                            book.IMG = binaryReader.ReadBytes(IMG.ContentLength);
                        }
                    }
                    db.Books.Add(book);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var validationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        System.Diagnostics.Debug.WriteLine($"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");
                    }
                }
                ModelState.AddModelError("", "Đã xảy ra lỗi khi lưu sách. Vui lòng kiểm tra chi tiết và thử lại.");
            }

            ViewBag.Author = new SelectList(db.Authors, "AuthorID", "AuthorName", book.Author);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.Author = new SelectList(db.Authors, "AuthorID", "AuthorName", book.Author);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Bookcode,Title,Author,GenreID,Price,Available,BookStatus,Publish")] Book book, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                // Handle file upload if MedicineImg is provided
                if (uploadImage != null && uploadImage.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        book.IMG = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                }

                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Author = new SelectList(db.Authors, "AuthorID", "AuthorName", book.Author);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", book.GenreID);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

qltv/Views/Books/Create.cshtml
@model qltv.Models.Book

@{
	<link href="~/Content/book.css" rel="stylesheet" />

	ViewBag.Title = "Create";
}




@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Add Book</h4>

		<div class="container">
			<div class="row row-cols-2">
				<div class="col">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.DropDownList("Author", null, htmlAttributes: new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
						</div>

					</div>
					<div class="form-group">
						@Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
						</div>
					</div>


					<div class="form-group">
						@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
						</div>
					</div>
				</div>
				<div class="col">
					<div class="form-group">
						@Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.BookStatus, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<div class="checkbox">
								@Html.EditorFor(model => model.BookStatus)
								@Html.ValidationMessageFor(model => model.BookStatus, "", new { @class = "text-danger" })
							</div>
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.Publish, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.Publish, "", new { @class = "text-danger" })
						</div>
					</div>


					<div class="form-group">
						@Html.LabelFor(model => model.IMG, "Book Image", htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<input type="file" name="IMG" class="form-control" />
							@Html.ValidationMessageFor(model => model.IMG, "", new { @class = "text-danger" })
						</div>
					</div>

				</div>


			</div>
		</div>

		<div class="form-group" style="display:flex;margin-top:30px;">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn btn-primary text-white" />
			</div>
			<div>

				@Html.ActionLink("Return", "Index", null, new { @class = "btn btn-outline-primary" })
			</div>
		</div>
	</div>
}



@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

qltv/Views/Books/Delete.cshtml
@model qltv.Models.Book

@{
	ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Book</h4>
	<hr />

	<div class="content">

		<div class="content">
			<div class="container">
				<div class="row">
					<div class="col-sm-5">
						@Html.HiddenFor(model => model.IMG)

						<dd>
							@if (Model.IMG != null && Model.IMG.Length > 0)
							{
								<img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.IMG)" alt="Book Image" style="max-width:200px;" />
							}
						</dd>
					</div>
					<div class="col-sm-4">
						<div class="row">
							<div class="col-8 col-sm-6">
								<dt>
									@Html.DisplayNameFor(model => model.Title)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Title)
								</dd>

								<dt>
									@Html.DisplayNameFor(model => model.Price)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Price)
								</dd>

								<dt>
									@Html.DisplayNameFor(model => model.Available)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Available)
								</dd>

								<dt>
									@Html.DisplayNameFor(model => model.BookStatus)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.BookStatus)
								</dd>


							</div>
							<div class="col-8 col-sm-6">
								<dt>
									@Html.DisplayNameFor(model => model.Publish)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Publish)
								</dd>



								<dt>
									@Html.DisplayNameFor(model => model.Author1.AuthorName)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Author1.AuthorName)
								</dd>

								<dt>
									@Html.DisplayNameFor(model => model.Genre.GenreName)
								</dt>

								<dd>
									@Html.DisplayFor(model => model.Genre.GenreName)
								</dd>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()
		<div class="position-fixed start-50 bottom-0 translate-middle-x w-100 zi-99 mb-3" style="max-width: 40rem;">
			<!-- Card -->
			<div class="card card-sm bg-dark border-dark mx-2">
				<div class="card-body">
					<div class="row justify-content-center justify-content-sm-between">
						<div class="col" style=" display: flex; align-items: center;">
							<input type="submit" value="Delete" class="btn btn-danger text-white" onclick="return confirmDelete()" />
						</div>
						<!-- End Col -->

						<div class="col-auto">
							<div class="d-flex gap-3">


								<button type="button" class="btn btn-ghost-light" style="color:#fff">  @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-ghost-light text-white" })</button>

							</div>
						</div>
						<!-- End Col -->
					</div>
					<!-- End Row -->
				</div>
			</div>
			<!-- End Card -->
		</div>


	}
</div>
<script type="text/javascript">
function confirmDelete() {
        return confirm("Bạn có chắc chắn muốn xóa không?");
    }</script>

qltv/Views/Books/Details.cshtml
@model qltv.Models.Book

@{
	ViewBag.Title = "Details";
	<link href="~/Content/book.css" rel="stylesheet" />
	<style>
		.height {
			height: 38px;
		}

		.width {
			width: 68px;
		}

		.btn-custom {
			translate: 0px 10px;
		}
	</style>
}

<h2>Detail Books</h2>

<div class="content">

	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-sm-5">
					@Html.HiddenFor(model => model.IMG)

					<dd>
						@if (Model.IMG != null && Model.IMG.Length > 0)
						{
							<img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.IMG)" alt="Book Image" style="max-width:200px;" />
						}
					</dd>
				</div>
				<div class="col-sm-4">
					<div class="row">
						<div class="col-8 col-sm-6">
							<dt>
								@Html.DisplayNameFor(model => model.Title)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Title)
							</dd>

							<dt>
								@Html.DisplayNameFor(model => model.Price)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Price)
							</dd>

							<dt>
								@Html.DisplayNameFor(model => model.Available)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Available)
							</dd>

							<dt>
								@Html.DisplayNameFor(model => model.BookStatus)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.BookStatus)
							</dd>


						</div>
						<div class="col-8 col-sm-6">
							<dt>
								@Html.DisplayNameFor(model => model.Publish)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Publish)
							</dd>



							<dt>
								@Html.DisplayNameFor(model => model.Author1.AuthorName)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Author1.AuthorName)
							</dd>

							<dt>
								@Html.DisplayNameFor(model => model.Genre.GenreName)
							</dt>

							<dd>
								@Html.DisplayFor(model => model.Genre.GenreName)
							</dd>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<h4>Borrow history</h4>
<div class="table-history-detail-book">
	<table style="margin-top:20px;" class="table table-bordered border-active">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Price)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Available)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.BookStatus)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Publish)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.IMG)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Author1.AuthorName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Genre.GenreName)
			</th>
			<th></th>
		</tr>


		<tr>
		</tr>


	</table>
</div>
<div class="position-fixed start-50 bottom-0 translate-middle-x w-100 zi-99 mb-3" style="max-width: 40rem;">
	<!-- Card -->
	<div class="card card-sm bg-dark border-dark mx-2">
		<div class="card-body">
			<div class="row justify-content-center justify-content-sm-between">
				<div class="col" style=" display: flex; align-items: center;">
					@Html.ActionLink("Delete", "Delete", new { id = Model.Bookcode }, new { @class = "btn btn-danger" })
				</div>
				<!-- End Col -->

				<div class="col-auto">
					<div class="d-flex gap-3">

						@Html.ActionLink("Edit", "Edit", new { id = Model.Bookcode }, new { @class = "btn btn-success height width" })  />
						<button type="button" class="btn btn-ghost-light" style="color:#fff">  @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-ghost-light text-white" })</button>

					</div>
				</div>
				<!-- End Col -->
			</div>
			<!-- End Row -->
		</div>
	</div>
	<!-- End Card -->
</div>

qltv/Views/Books/Edit.cshtml
@model qltv.Models.Book

@{
	ViewBag.Title = "Edit";
}
<style>
	.margin-top {
		margin-top: 20px;
	}

	.margin-top-10 {
		margin-top: 10px;
	}
</style>
<h2>Edit Book</h2>


@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">

		<!-- Section: Split screen -->
		<section class="">

			<div class="container-fluid px-0">
				<div class="row g-0">

					<!-- First column -->
					<div class="col-md-6 vh-80">
						@Html.ValidationSummary(true, "", new { @class = "text-danger" })
						@Html.HiddenFor(model => model.Bookcode)

						<div class="form-group " style="margin-top:30px;">
							@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group margin-top">
							@Html.LabelFor(model => model.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.DropDownList("Author", null, htmlAttributes: new { @class = "form-control" })
								@Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group  margin-top">
							@Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
								@Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
							</div>
						</div>
						<div class="form-group margin-top">
							@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
							</div>
						</div>

						<div class="form-group margin-top">
							@Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.Available, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
							</div>
						</div>
					</div>
					<!-- First column -->
					<!-- Second column -->
					<div class="col-md-6 vh-100">
						<div class="form-group margin-top-10">
							@Html.LabelFor(model => model.IMG, "Upload Image", htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								<input type="file" name="uploadImage" id="uploadImage" />
							</div>
						</div>

						<div class="form-group margin-top-10">
							@Html.LabelFor(model => model.BookStatus, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								<div class="checkbox">
									@Html.EditorFor(model => model.BookStatus)
									@Html.ValidationMessageFor(model => model.BookStatus, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="form-group margin-top-10">
							@Html.LabelFor(model => model.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
							<div class="col-md-10">
								@Html.EditorFor(model => model.Publish, new { htmlAttributes = new { @class = "form-control" } })
								@Html.ValidationMessageFor(model => model.Publish, "", new { @class = "text-danger" })
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10 margin-top-10">
								<input type="submit" value="Save" class="btn btn-outline-primary" />
							</div>
						</div>
					</div>
					<!-- Second column -->

				</div>
			</div>

		</section>
		<!-- Section: Split screen -->
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}